Lab 111
noemabbbg/IU5-iOS-2022 pull request #2
Opened 2022-02-27 21:00 UTC by noemabbbg

## Товарищ, твой PR - твоя гордость!

- [ ] Убедись, что все тесты прошли успешно.
- [ ] Проверь, что Pull Request таргетоирован в ТВОЙ ФОРКНУТЫЙ main
- [ ] Заполни отчет по лабораторной работе в Google форме
- [ ] Улыбнись, ведь ты приобрел новые навыки)

## Важно!

После того, как ты заполнишь отчет по лабе, я или Юра поревьюим его, и напишем комментарии к коду, если будут вопросы.

Когда ты увидишь коментарий "Все ОК, мержи", можешь смержить PR.

- [ ] Ты увидел "Все ОК, мержи"?

2022-02-28 20:42 UTC, MrOcumare requested changes

2022-02-28 20:42 UTC, MrOcumare commented on LABS/LAB_1/ArrayToString.swift
> +                     return ""
ой ой ой, сказал code style 
дружище не надо так

2022-02-28 20:42 UTC, MrOcumare commented on LABS/LAB_1/ArrayToString.swift
> +                 guard array.count > 1 else {
тут не питон)
табуляция н нужна)

2022-02-28 20:42 UTC, MrOcumare commented on LABS/LAB_1/ArrayToString.swift
> +                         var first = 1
first что?)

давай попробуем придумать подходящее имя)

2022-02-28 20:42 UTC, MrOcumare commented on LABS/LAB_1/ArrayToString.swift
> +                   if( i == array.count-1 && numElement == 0){
Вы с товарищем Давиташвили вместе делали?

2022-02-28 20:42 UTC, MrOcumare commented on LABS/LAB_1/ArrayToString.swift
> +        return str
В целом алгоритм ок,
но поработай на code style
в первой лабе не буду балы снимать за оформление, но со следующей начнем

2022-02-28 20:42 UTC, MrOcumare commented on LABS/LAB_1/BooleanConverter.swift
> +        switch string {
у switch case не такой код стайл, дружище 

switch string {
case "YES":
    // code
code "NO":
}

2022-02-28 20:42 UTC, MrOcumare commented on LABS/LAB_1/NumberToArray.swift
> +                 return newArr.reversed()
так же все очень плохо с оформлением

2022-02-28 20:42 UTC, MrOcumare commented on LABS/LAB_1/SquareSum.swift
> +        var k = 0
не, давай сразу учиться придумывать хорошие названия)

2022-02-28 20:42 UTC, MrOcumare commented on LABS/LAB_1/SquareSum.swift
> +        let arr = [Int]()
а зачем он нужон?

2022-02-28 20:42 UTC, MrOcumare commented on LABS/LAB_1/SquareSum.swift
> +        if arrayOfNumber == arr { return 0} //.isEmpty
guard arrayOfNumber.count != 0 else {
    return 0
}
что за танцы с бубном?)

2022-02-28 20:42 UTC, MrOcumare commented on LABS/LAB_1/SquareSum.swift
> +                k += arrayOfNumber[i]*arrayOfNumber[i] //pow(Double(k),2)
так есть же функция степени в языке swift)

2022-02-28 20:42 UTC, MrOcumare commented on LABS/LAB_1/SquareSum.swift
> +        return k
тоже codestyle плачет

2022-02-28 20:42 UTC, MrOcumare commented on LABS/LAB_1/SquareSum.swift
> +        if arrayOfNumber == arr { return 0} //.isEmpty
и можно в принципе без проверки сделать

2022-02-28 20:42 UTC, MrOcumare commented on LABS/LAB_1/SequenceСreator.swift
> +
с codestyle беда

2022-02-28 20:42 UTC, MrOcumare commented on LABS/LAB_1/SequenceСreator.swift
> +                 }
с codestyle беда

2022-02-28 20:50 UTC, MrOcumare commented on LABS/LAB_1/SquareSum.swift
> +        return k
Комментарии к коду если и писать то сверху, а не с боку)
swift - мощный язык и в нем есть почти все что нужно из стандартных команд/операций 
лучше не городить велосипеды)

2022-02-28 20:51 UTC, MrOcumare commented
needs work

2022-02-28 20:51 UTC, MrOcumare commented
Не забывай проставлять галочки

2022-03-01 11:01 UTC, YuryBogdanov commented
https://github.com/raywenderlich/swift-style-guide

2022-03-01 11:03 UTC, noemabbbg commented
> https://github.com/raywenderlich/swift-style-guide

Посмотрю и исправлю, спасибо

2022-03-01 19:56 UTC, MrOcumare requested changes

2022-03-01 19:56 UTC, MrOcumare commented on LABS/LAB_1/BooleanConverter.swift
> +             default:
вот тут default не нужон 
перепиши на case veryBad(value: String)

2022-03-05 18:28 UTC, noemabbbg reviewed
b

2022-03-06 20:09 UTC, merged